# Generated by Django 4.0.3 on 2022-03-18 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eje_description', models.CharField(max_length=100, verbose_name='Eje')),
            ],
            options={
                'verbose_name': 'Eje',
                'verbose_name_plural': 'Ejes',
                'db_table': 'Eje',
                'ordering': ['eje_description'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador_description', models.CharField(max_length=100, unique=True, verbose_name='Indicador de Gestión')),
            ],
            options={
                'verbose_name': 'Indicador de Gestión',
                'verbose_name_plural': 'Indicadores de Gestión',
                'db_table': 'IndicadorGestion',
                'ordering': ['indicador_description'],
            },
        ),
        migrations.CreateModel(
            name='MedioVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_description', models.CharField(max_length=100, unique=True, verbose_name='Medio de Verificación')),
            ],
            options={
                'verbose_name': 'Medio de Verificación',
                'verbose_name_plural': 'Medios de Verificación',
                'db_table': 'MedioVerificacion',
                'ordering': ['medio_description'],
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_name', models.CharField(max_length=100, verbose_name='Mes')),
            ],
            options={
                'verbose_name': 'Mes',
                'verbose_name_plural': 'Meses',
                'db_table': 'Mes',
                'ordering': ['mes_name'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operativo_description', models.TextField(verbose_name='Objetivo Operativo')),
            ],
            options={
                'verbose_name': 'Objetivo Operativo',
                'verbose_name_plural': 'Objetivos Operativos',
                'db_table': 'ObjetivoOperativo',
                'ordering': ['operativo_description'],
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_description', models.TextField(verbose_name='Objetivo')),
                ('objetivo_eje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.eje', verbose_name='Eje')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'db_table': 'Objetivo',
                'ordering': ['objetivo_description'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(verbose_name='Meta')),
                ('meta_operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.objetivooperativo', verbose_name='Objetivo Operativo')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'db_table': 'Meta',
                'ordering': ['meta_description'],
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea_description', models.TextField(verbose_name='Línea de Actuación')),
                ('linea_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.objetivo', verbose_name='Objetivo')),
            ],
            options={
                'verbose_name': 'Línea',
                'verbose_name_plural': 'Línea',
                'db_table': 'Linea',
                'ordering': ['linea_description'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_description', models.TextField(verbose_name='Actividad')),
                ('actividad_presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Presupuesto')),
                ('actividad_indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.indicadorgestion', verbose_name='Indicador de Gestión')),
                ('actividad_medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.medioverificacion', verbose_name='Medio de Verificación')),
                ('actividad_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.meta', verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'Actividad',
                'ordering': ['actividad_description'],
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.actividad', verbose_name='Actividad')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.mes', verbose_name='Mes')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronogramas',
                'db_table': 'Cronograma',
                'ordering': ['mes'],
                'unique_together': {('actividad', 'mes')},
            },
        ),
    ]
