# Generated by Django 4.0.3 on 2022-03-19 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poa', '0003_alter_indicadorgestion_indicador_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POAEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_name', models.CharField(max_length=100, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'Estado',
                'ordering': ['estado_name'],
            },
        ),
        migrations.AddField(
            model_name='objetivooperativo',
            name='operativo_linea',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poa.linea', verbose_name='Linea'),
        ),
        migrations.CreateModel(
            name='POA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poa_fecha_modificacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha modificación')),
                ('poa_presentacion', models.TextField(verbose_name='Presentación')),
                ('poa_notas', models.TextField(verbose_name='Notas')),
                ('poa_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.poaestado', verbose_name='Estado')),
                ('poa_user_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'POA',
                'verbose_name_plural': 'POA',
                'db_table': 'POA',
                'ordering': ['poa_estado'],
            },
        ),
        migrations.AddField(
            model_name='objetivooperativo',
            name='operativo_poa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poa.poa', verbose_name='POA'),
        ),
        migrations.AlterUniqueTogether(
            name='objetivooperativo',
            unique_together={('operativo_poa', 'operativo_linea')},
        ),
    ]
