# Generated by Django 4.0.3 on 2022-03-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0004_poaestado_objetivooperativo_operativo_linea_poa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivooperativo',
            name='operativo_linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.linea', verbose_name='Linea'),
        ),
        migrations.AlterField(
            model_name='objetivooperativo',
            name='operativo_poa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.poa', verbose_name='POA'),
        ),
    ]
