# Generated by Django 4.0.3 on 2022-03-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0005_alter_objetivooperativo_operativo_linea_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poa',
            options={'ordering': ['poa_notas'], 'verbose_name': 'POA', 'verbose_name_plural': 'POA'},
        ),
        migrations.RemoveField(
            model_name='poa',
            name='poa_estado',
        ),
        migrations.DeleteModel(
            name='POAEstado',
        ),
    ]
