# Generated by Django 4.0.3 on 2022-03-24 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0007_poaestado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='POAEstado',
        ),
    ]
