# Generated by Django 4.0.3 on 2022-03-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0008_delete_poaestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_name', models.CharField(max_length=100, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'Estado',
                'ordering': ['estado_name'],
            },
        ),
    ]
