# Generated by Django 4.0.3 on 2022-03-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0009_poaestado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='poaestado',
            table='POAEstado',
        ),
    ]
