# Generated by Django 4.0.3 on 2022-03-25 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0011_poa_poa_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poa',
            options={'ordering': ['poa_estado'], 'verbose_name': 'POA', 'verbose_name_plural': 'POA'},
        ),
    ]
