# Generated by Django 4.0.3 on 2022-03-25 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0015_coordinacion_coordinacion_cargo'),
        ('poa', '0012_alter_poa_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='POAVicerrectoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poavicerrectoria_anno', models.IntegerField(default=2022, verbose_name='Año')),
                ('poavicerrectoria_poa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.poa', verbose_name='POA')),
                ('poavicerrectoria_vice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.vicerrectoria', verbose_name='Vicerrectoría')),
            ],
            options={
                'verbose_name': 'POAVicerrectoria',
                'verbose_name_plural': 'POAVicerrectoria',
                'db_table': 'POAVicerrectoria',
                'ordering': ['poavicerrectoria_anno'],
                'unique_together': {('poavicerrectoria_anno', 'poavicerrectoria_vice')},
            },
        ),
    ]
