# Generated by Django 4.0.3 on 2022-03-25 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0015_coordinacion_coordinacion_cargo'),
        ('poa', '0013_poavicerrectoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='POAUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poaunidad_anno', models.IntegerField(default=2022, verbose_name='Año')),
                ('poaunidad_poa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.poa', verbose_name='POA')),
                ('poaunidad_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.vicerrectoria', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'POAUnidad',
                'verbose_name_plural': 'POAUnidad',
                'db_table': 'POAUnidad',
                'ordering': ['poaunidad_anno'],
                'unique_together': {('poaunidad_anno', 'poaunidad_unidad')},
            },
        ),
        migrations.CreateModel(
            name='POAEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poaescuela_anno', models.IntegerField(default=2022, verbose_name='Año')),
                ('poaescuela_escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.vicerrectoria', verbose_name='Escuela')),
                ('poaescuela_poa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.poa', verbose_name='POA')),
            ],
            options={
                'verbose_name': 'POAEscuela',
                'verbose_name_plural': 'POAEscuela',
                'db_table': 'POAEscuela',
                'ordering': ['poaescuela_anno'],
                'unique_together': {('poaescuela_anno', 'poaescuela_escuela')},
            },
        ),
        migrations.CreateModel(
            name='POADireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poadireccion_anno', models.IntegerField(default=2022, verbose_name='Año')),
                ('poadireccion_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.vicerrectoria', verbose_name='Direccion')),
                ('poadireccion_poa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.poa', verbose_name='POA')),
            ],
            options={
                'verbose_name': 'POADireccion',
                'verbose_name_plural': 'POADireccion',
                'db_table': 'POADireccion',
                'ordering': ['poadireccion_anno'],
                'unique_together': {('poadireccion_anno', 'poadireccion_direccion')},
            },
        ),
        migrations.CreateModel(
            name='POADepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poadepartamento_anno', models.IntegerField(default=2022, verbose_name='Año')),
                ('poadepartamento_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.vicerrectoria', verbose_name='Departamento')),
                ('poadepartamento_poa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.poa', verbose_name='POA')),
            ],
            options={
                'verbose_name': 'POADepartamento',
                'verbose_name_plural': 'POADepartamento',
                'db_table': 'POADepartamento',
                'ordering': ['poadepartamento_anno'],
                'unique_together': {('poadepartamento_anno', 'poadepartamento_departamento')},
            },
        ),
        migrations.CreateModel(
            name='POACoordinacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poacoordinacion_anno', models.IntegerField(default=2022, verbose_name='Año')),
                ('poacoordinacion_coordinacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.vicerrectoria', verbose_name='Coordinacion')),
                ('poacoordinacion_poa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.poa', verbose_name='POA')),
            ],
            options={
                'verbose_name': 'POACoordinacion',
                'verbose_name_plural': 'POACoordinacion',
                'db_table': 'POACoordinacion',
                'ordering': ['poacoordinacion_anno'],
                'unique_together': {('poacoordinacion_anno', 'poacoordinacion_coordinacion')},
            },
        ),
    ]
