# Generated by Django 4.0.3 on 2022-03-25 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0015_coordinacion_coordinacion_cargo'),
        ('poa', '0014_poaunidad_poaescuela_poadireccion_poadepartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poacoordinacion',
            name='poacoordinacion_coordinacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.coordinacion', verbose_name='Coordinacion'),
        ),
        migrations.AlterField(
            model_name='poadepartamento',
            name='poadepartamento_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='poadireccion',
            name='poadireccion_direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.direccion', verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='poaescuela',
            name='poaescuela_escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.escuela', verbose_name='Escuela'),
        ),
        migrations.AlterField(
            model_name='poaunidad',
            name='poaunidad_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.unidad', verbose_name='Unidad'),
        ),
    ]
