# Generated by Django 4.0.3 on 2022-03-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0015_alter_poacoordinacion_poacoordinacion_coordinacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poa',
            options={'ordering': ['poa_name'], 'verbose_name': 'POA', 'verbose_name_plural': 'POA'},
        ),
        migrations.AddField(
            model_name='poa',
            name='poa_name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
