# Generated by Django 4.0.3 on 2022-03-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0016_alter_poa_options_poa_poa_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poa',
            name='poa_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
