# Generated by Django 4.0.3 on 2022-03-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0017_alter_poa_poa_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poa',
            name='poa_notas',
            field=models.TextField(null=True, verbose_name='Notas'),
        ),
    ]
