# Generated by Django 4.0.3 on 2022-04-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0018_alter_poa_poa_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorgestion',
            name='indicador_code',
            field=models.CharField(blank=True, max_length=3, unique=True, verbose_name='Código Indicador de Gestión'),
        ),
        migrations.AddField(
            model_name='medioverificacion',
            name='medio_code',
            field=models.CharField(blank=True, max_length=3, unique=True, verbose_name='Código Medio de Verificación'),
        ),
    ]
