# Generated by Django 4.0.3 on 2022-04-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0020_alter_indicadorgestion_indicador_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicadorgestion',
            name='indicador_code',
        ),
        migrations.RemoveField(
            model_name='medioverificacion',
            name='medio_code',
        ),
    ]
