# Generated by Django 4.0.3 on 2022-04-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0021_remove_indicadorgestion_indicador_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poa',
            name='poa_estamento',
            field=models.CharField(max_length=100, null=True, verbose_name='Estamento'),
        ),
        migrations.AlterField(
            model_name='poa',
            name='poa_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='poa',
            unique_together={('poa_name', 'poa_estamento')},
        ),
    ]
