# Generated by Django 4.0.3 on 2022-04-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0022_poa_poa_estamento_alter_poa_poa_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poa',
            name='poa_estamento',
            field=models.CharField(default='', max_length=100, verbose_name='Estamento'),
        ),
    ]
