# Generated by Django 4.0.3 on 2022-04-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0019_alter_cargo_cargo_code'),
        ('poa', '0024_alter_poa_poa_estamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poa',
            options={'ordering': ['poa_anno'], 'verbose_name': 'POA', 'verbose_name_plural': 'POA'},
        ),
        migrations.AlterModelOptions(
            name='poacoordinacion',
            options={'ordering': ['poacoordinacion_poa'], 'verbose_name': 'POACoordinacion', 'verbose_name_plural': 'POACoordinacion'},
        ),
        migrations.AlterModelOptions(
            name='poadepartamento',
            options={'ordering': ['poadepartamento_poa'], 'verbose_name': 'POADepartamento', 'verbose_name_plural': 'POADepartamento'},
        ),
        migrations.AlterModelOptions(
            name='poadireccion',
            options={'ordering': ['poadireccion_poa'], 'verbose_name': 'POADireccion', 'verbose_name_plural': 'POADireccion'},
        ),
        migrations.AlterModelOptions(
            name='poaescuela',
            options={'ordering': ['poaescuela_poa'], 'verbose_name': 'POAEscuela', 'verbose_name_plural': 'POAEscuela'},
        ),
        migrations.AlterModelOptions(
            name='poaunidad',
            options={'ordering': ['poaunidad_poa'], 'verbose_name': 'POAUnidad', 'verbose_name_plural': 'POAUnidad'},
        ),
        migrations.AlterModelOptions(
            name='poavicerrectoria',
            options={'ordering': ['poavicerrectoria_poa'], 'verbose_name': 'POAVicerrectoria', 'verbose_name_plural': 'POAVicerrectoria'},
        ),
        migrations.AlterUniqueTogether(
            name='poa',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='poa',
            name='poa_anno',
            field=models.IntegerField(default=2022, verbose_name='Año'),
        ),
        migrations.AlterUniqueTogether(
            name='poacoordinacion',
            unique_together={('poacoordinacion_poa', 'poacoordinacion_coordinacion')},
        ),
        migrations.AlterUniqueTogether(
            name='poadepartamento',
            unique_together={('poadepartamento_poa', 'poadepartamento_departamento')},
        ),
        migrations.AlterUniqueTogether(
            name='poadireccion',
            unique_together={('poadireccion_poa', 'poadireccion_direccion')},
        ),
        migrations.AlterUniqueTogether(
            name='poaescuela',
            unique_together={('poaescuela_poa', 'poaescuela_escuela')},
        ),
        migrations.AlterUniqueTogether(
            name='poaunidad',
            unique_together={('poaunidad_poa', 'poaunidad_unidad')},
        ),
        migrations.AlterUniqueTogether(
            name='poavicerrectoria',
            unique_together={('poavicerrectoria_poa', 'poavicerrectoria_vice')},
        ),
        migrations.RemoveField(
            model_name='poa',
            name='poa_name',
        ),
        migrations.RemoveField(
            model_name='poacoordinacion',
            name='poacoordinacion_anno',
        ),
        migrations.RemoveField(
            model_name='poadepartamento',
            name='poadepartamento_anno',
        ),
        migrations.RemoveField(
            model_name='poadireccion',
            name='poadireccion_anno',
        ),
        migrations.RemoveField(
            model_name='poaescuela',
            name='poaescuela_anno',
        ),
        migrations.RemoveField(
            model_name='poaunidad',
            name='poaunidad_anno',
        ),
        migrations.RemoveField(
            model_name='poavicerrectoria',
            name='poavicerrectoria_anno',
        ),
    ]
