# Generated by Django 4.0.3 on 2022-04-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0025_alter_poa_options_alter_poacoordinacion_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poa',
            unique_together={('poa_anno', 'poa_estamento')},
        ),
    ]
