# Generated by Django 4.0.3 on 2022-04-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0026_alter_poa_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mes',
            options={'ordering': ['mes_number'], 'verbose_name': 'Mes', 'verbose_name_plural': 'Meses'},
        ),
        migrations.AddField(
            model_name='mes',
            name='mes_number',
            field=models.IntegerField(default=1, verbose_name='Mes'),
        ),
    ]
