# Generated by Django 4.0.3 on 2022-04-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0027_alter_mes_options_mes_mes_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mes',
            name='mes_number',
            field=models.IntegerField(verbose_name='Mes'),
        ),
    ]
