# Generated by Django 4.0.3 on 2022-04-09 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poa', '0028_alter_mes_mes_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_description', models.CharField(max_length=100, unique=True, verbose_name='Responsable')),
                ('responsable_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsable',
                'db_table': 'Responsable',
                'ordering': ['responsable_description'],
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='actividad_responsable',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='poa.responsable', verbose_name='Responsable'),
        ),
    ]
