# Generated by Django 4.0.3 on 2022-04-09 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0029_responsable_actividad_actividad_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='actividad_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.responsable', verbose_name='Responsable'),
        ),
    ]
