# Generated by Django 4.0.3 on 2022-04-09 21:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poa', '0030_alter_actividad_actividad_responsable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicadorgestion',
            unique_together={('indicador_description', 'indicador_user')},
        ),
        migrations.AlterUniqueTogether(
            name='medioverificacion',
            unique_together={('medio_description', 'medio_user')},
        ),
        migrations.AlterUniqueTogether(
            name='responsable',
            unique_together={('responsable_description', 'responsable_user')},
        ),
    ]
