# Generated by Django 4.0.3 on 2022-04-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0031_alter_indicadorgestion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronograma',
            options={'ordering': ['cronograma_mes'], 'verbose_name': 'Cronograma', 'verbose_name_plural': 'Cronogramas'},
        ),
        migrations.RenameField(
            model_name='cronograma',
            old_name='actividad',
            new_name='cronograma_actividad',
        ),
        migrations.RenameField(
            model_name='cronograma',
            old_name='mes',
            new_name='cronograma_mes',
        ),
        migrations.AlterUniqueTogether(
            name='cronograma',
            unique_together={('cronograma_actividad', 'cronograma_mes')},
        ),
    ]
