# Generated by Django 4.0.3 on 2022-04-12 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0032_alter_cronograma_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='actividad_indicador',
        ),
        migrations.AddField(
            model_name='meta',
            name='meta_indicador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poa.indicadorgestion', verbose_name='Indicador de Gestión'),
        ),
    ]
