# Generated by Django 4.0.3 on 2022-04-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0033_remove_actividad_actividad_indicador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='meta_indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.indicadorgestion', verbose_name='Indicador de Gestión'),
        ),
    ]
