# Generated by Django 4.0.3 on 2022-04-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0034_alter_meta_meta_indicador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='linea',
            options={'ordering': ['linea_objetivo'], 'verbose_name': 'Línea', 'verbose_name_plural': 'Línea'},
        ),
        migrations.AlterModelOptions(
            name='meta',
            options={'verbose_name': 'Meta', 'verbose_name_plural': 'Metas'},
        ),
        migrations.AlterModelOptions(
            name='objetivo',
            options={'ordering': ['objetivo_eje'], 'verbose_name': 'Objetivo', 'verbose_name_plural': 'Objetivos'},
        ),
        migrations.AlterModelOptions(
            name='objetivooperativo',
            options={'verbose_name': 'Objetivo Operativo', 'verbose_name_plural': 'Objetivos Operativos'},
        ),
    ]
