# Generated by Django 4.0.3 on 2022-04-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0035_alter_actividad_options_alter_linea_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poadepartamento',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='poadepartamento',
            name='poadepartamento_departamento',
        ),
        migrations.RemoveField(
            model_name='poadepartamento',
            name='poadepartamento_poa',
        ),
        migrations.AlterUniqueTogether(
            name='poadireccion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='poadireccion',
            name='poadireccion_direccion',
        ),
        migrations.RemoveField(
            model_name='poadireccion',
            name='poadireccion_poa',
        ),
        migrations.AlterUniqueTogether(
            name='poaescuela',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='poaescuela',
            name='poaescuela_escuela',
        ),
        migrations.RemoveField(
            model_name='poaescuela',
            name='poaescuela_poa',
        ),
        migrations.AlterUniqueTogether(
            name='poaunidad',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='poaunidad',
            name='poaunidad_poa',
        ),
        migrations.RemoveField(
            model_name='poaunidad',
            name='poaunidad_unidad',
        ),
        migrations.AlterUniqueTogether(
            name='poavicerrectoria',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='poavicerrectoria',
            name='poavicerrectoria_poa',
        ),
        migrations.RemoveField(
            model_name='poavicerrectoria',
            name='poavicerrectoria_vice',
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['id'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='meta',
            options={'ordering': ['id'], 'verbose_name': 'Meta', 'verbose_name_plural': 'Metas'},
        ),
        migrations.AlterModelOptions(
            name='objetivooperativo',
            options={'ordering': ['id'], 'verbose_name': 'Objetivo Operativo', 'verbose_name_plural': 'Objetivos Operativos'},
        ),
        migrations.DeleteModel(
            name='POACoordinacion',
        ),
        migrations.DeleteModel(
            name='POADepartamento',
        ),
        migrations.DeleteModel(
            name='POADireccion',
        ),
        migrations.DeleteModel(
            name='POAEscuela',
        ),
        migrations.DeleteModel(
            name='POAUnidad',
        ),
        migrations.DeleteModel(
            name='POAVicerrectoria',
        ),
    ]
