# Generated by Django 4.0.3 on 2022-04-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0036_alter_poadepartamento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poa',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='poa',
            name='poa_estamento',
        ),
    ]
