# Generated by Django 4.0.3 on 2022-04-25 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0024_remove_coordinacion_coordinacion_cargo_and_more'),
        ('poa', '0037_alter_poa_unique_together_remove_poa_poa_estamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='poa',
            name='poa_estamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uapa.estamento', verbose_name='Estamento'),
        ),
        migrations.AlterUniqueTogether(
            name='poa',
            unique_together={('poa_anno', 'poa_estamento')},
        ),
    ]
