# Generated by Django 4.0.3 on 2022-04-25 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0024_remove_coordinacion_coordinacion_cargo_and_more'),
        ('poa', '0039_alter_poa_poa_estamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poa',
            name='poa_estamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.estamento', verbose_name='Estamento'),
        ),
    ]
