# Generated by Django 4.0.3 on 2022-05-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0040_alter_poa_poa_estamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eje',
            options={'ordering': ['id'], 'verbose_name': 'Eje', 'verbose_name_plural': 'Ejes'},
        ),
        migrations.AlterModelOptions(
            name='linea',
            options={'ordering': ['id'], 'verbose_name': 'Línea', 'verbose_name_plural': 'Línea'},
        ),
        migrations.AlterModelOptions(
            name='objetivo',
            options={'ordering': ['id'], 'verbose_name': 'Objetivo', 'verbose_name_plural': 'Objetivos'},
        ),
        migrations.AlterUniqueTogether(
            name='objetivooperativo',
            unique_together={('operativo_poa', 'operativo_linea', 'operativo_description')},
        ),
    ]
