# Generated by Django 4.0.3 on 2022-06-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0041_alter_eje_options_alter_linea_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eje',
            options={'ordering': ['eje_description'], 'verbose_name': 'Eje', 'verbose_name_plural': 'Ejes'},
        ),
        migrations.AlterModelOptions(
            name='linea',
            options={'ordering': ['linea_description'], 'verbose_name': 'Línea', 'verbose_name_plural': 'Línea'},
        ),
        migrations.AlterModelOptions(
            name='objetivo',
            options={'ordering': ['objetivo_description'], 'verbose_name': 'Objetivo', 'verbose_name_plural': 'Objetivos'},
        ),
        migrations.AlterModelOptions(
            name='objetivooperativo',
            options={'ordering': ['operativo_linea'], 'verbose_name': 'Objetivo Operativo', 'verbose_name_plural': 'Objetivos Operativos'},
        ),
        migrations.RemoveField(
            model_name='meta',
            name='meta_indicador',
        ),
        migrations.AddField(
            model_name='actividad',
            name='actividad_cumplimiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Cumplimiento'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='actividad_peso',
            field=models.IntegerField(default=0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='actividad_medio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.medioverificacion', verbose_name='Indicador Verificable'),
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia_description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('evidencia_file', models.FileField(blank=True, upload_to='evidencias', verbose_name='Evidencia')),
                ('evidencia_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.actividad', verbose_name='Actividad')),
            ],
        ),
    ]
