# Generated by Django 4.0.3 on 2022-06-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0042_alter_eje_options_alter_linea_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='actividad_cumplimiento',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='cronograma_cumplimiento',
            field=models.BooleanField(default=False, verbose_name='Cumplimiento'),
        ),
    ]
