# Generated by Django 4.0.3 on 2022-06-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0045_alter_evidencia_evidencia_cronograma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evidencia',
        ),
    ]
