# Generated by Django 4.0.3 on 2022-06-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0046_delete_evidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia_description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('evidencia_file', models.FileField(blank=True, upload_to='evidencias', verbose_name='Evidencia')),
                ('evidencia_cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.cronograma', verbose_name='Cronograma')),
            ],
        ),
    ]
