# Generated by Django 4.0.3 on 2022-06-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0049_evidencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evidencia',
        ),
    ]
