# Generated by Django 4.0.3 on 2022-06-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0051_evidencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronograma',
            options={'ordering': ['id'], 'verbose_name': 'Cronograma', 'verbose_name_plural': 'Cronogramas'},
        ),
    ]
