# Generated by Django 4.0.3 on 2022-06-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0052_alter_cronograma_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidencia',
            options={'ordering': ['evidencia_cronograma'], 'verbose_name': 'Evidencia', 'verbose_name_plural': 'Evidencias'},
        ),
        migrations.AddField(
            model_name='cronograma',
            name='cronograma_notas',
            field=models.TextField(default='', verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='cronograma_presupuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Presupuesto Gastado'),
        ),
        migrations.AlterField(
            model_name='poa',
            name='poa_notas',
            field=models.TextField(default='', verbose_name='Notas'),
        ),
    ]
