# Generated by Django 4.0.3 on 2022-08-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0053_alter_evidencia_options_cronograma_cronograma_notas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objetivooperativo',
            options={'ordering': ['operativo_linea', 'id'], 'verbose_name': 'Objetivo Operativo', 'verbose_name_plural': 'Objetivos Operativos'},
        ),
        migrations.DeleteModel(
            name='IndicadorGestion',
        ),
    ]
