# Generated by Django 4.0.3 on 2022-12-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0054_alter_objetivooperativo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poa',
            name='poa_include_subs',
            field=models.BooleanField(default=False, verbose_name='Incluir subordinados'),
        ),
    ]
