# Generated by Django 4.0.3 on 2023-10-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0055_poa_poa_include_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poa',
            name='poa_anno',
            field=models.IntegerField(default=2023, verbose_name='Año'),
        ),
    ]
