# Generated by Django 4.0.3 on 2024-02-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0056_alter_poa_poa_anno'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='actividad_order',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='meta',
            name='meta_order',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='objetivooperativo',
            name='operativo_order',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='poa',
            name='poa_anno',
            field=models.IntegerField(default=2024, verbose_name='Año'),
        ),
    ]
