# Generated by Django 4.0.3 on 2024-03-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0057_actividad_actividad_order_meta_meta_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['actividad_order'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='meta',
            options={'ordering': ['meta_order'], 'verbose_name': 'Meta', 'verbose_name_plural': 'Metas'},
        ),
        migrations.AlterModelOptions(
            name='objetivooperativo',
            options={'ordering': ['operativo_order'], 'verbose_name': 'Objetivo Operativo', 'verbose_name_plural': 'Objetivos Operativos'},
        ),
        migrations.RemoveField(
            model_name='poa',
            name='poa_presentacion',
        ),
    ]
