# Generated by Django 4.0.3 on 2024-03-05 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poa', '0058_alter_actividad_options_alter_meta_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('log_description', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
                ('log_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'Log',
                'ordering': ['log_date'],
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('bug_origin', models.CharField(max_length=100, unique=True, verbose_name='Origen')),
                ('bug_description', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
                ('bug_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Bug',
                'verbose_name_plural': 'Bugs',
                'db_table': 'Bug',
                'ordering': ['bug_date'],
            },
        ),
    ]
