# Generated by Django 4.0.3 on 2024-03-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0059_log_bug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_description',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_origin',
            field=models.CharField(max_length=100, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_description',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
    ]
