# Generated by Django 4.0.3 on 2024-03-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0060_alter_bug_bug_description_alter_bug_bug_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='meta_selected',
            field=models.BooleanField(default=False, verbose_name='Seleccionada'),
        ),
        migrations.AddField(
            model_name='objetivooperativo',
            name='operativo_selected',
            field=models.BooleanField(default=False, verbose_name='Seleccionado'),
        ),
    ]
