# Generated by Django 4.0.3 on 2024-03-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0061_meta_meta_selected_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsable',
            options={'ordering': ['responsable_description'], 'verbose_name': 'Responsable', 'verbose_name_plural': 'Responsables'},
        ),
    ]
