# Generated by Django 4.0.3 on 2024-03-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0062_alter_responsable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_description', models.TextField(verbose_name='Nota')),
                ('nota_itemid', models.IntegerField(default=0, verbose_name='Id')),
                ('nota_itemname', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'Nota',
                'ordering': ['nota_itemname'],
            },
        ),
        migrations.AlterField(
            model_name='eje',
            name='eje_description',
            field=models.TextField(verbose_name='Eje'),
        ),
    ]
