# Generated by Django 4.0.3 on 2024-03-15 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poa', '0063_nota_alter_eje_eje_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='nota_poa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poa.poa', verbose_name='POA'),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
