# Generated by Django 4.0.3 on 2024-03-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0065_alter_nota_nota_itemid_alter_nota_nota_itemname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poa',
            name='poa_notas',
        ),
    ]
