# Generated by Django 4.0.3 on 2024-03-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0067_alter_nota_options_nota_nota_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crono_title', models.CharField(max_length=100, null=True, verbose_name='Título')),
                ('crono_description', models.TextField(verbose_name='Descripción')),
                ('crono_order', models.IntegerField(default=0, null=True, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'CronogramaGeneral',
                'verbose_name_plural': 'Cronogramas Generales',
                'db_table': 'CronogramaGeneral',
                'ordering': ['crono_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['nota_itemname', 'nota_date'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
    ]
