# Generated by Django 4.0.3 on 2024-03-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0068_cronogramageneral_alter_nota_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='nota_checked',
            field=models.BooleanField(default=False, verbose_name='Cumplimiento'),
        ),
    ]
