# Generated by Django 4.0.3 on 2024-03-20 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0070_alter_bug_bug_date_alter_log_log_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticia_title', models.CharField(max_length=100, null=True, verbose_name='Título')),
                ('noticia_description', models.TextField(verbose_name='Descripción')),
                ('noticia_start', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha inicio')),
                ('noticia_end', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha inicio')),
                ('noticia_always', models.BooleanField(default=False, verbose_name='Mostrar siempre')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'db_table': 'Noticia',
                'ordering': ['noticia_start'],
            },
        ),
        migrations.DeleteModel(
            name='CronogramaGeneral',
        ),
    ]
