# Generated by Django 4.0.3 on 2024-03-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0034_colaborador_colaborador_unique_colaborador'),
        ('poa', '0071_noticia_delete_cronogramageneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tableau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableau_title', models.CharField(max_length=100, null=True, verbose_name='Título')),
                ('tableau_description', models.TextField(verbose_name='Descripción')),
                ('tableau_url', models.TextField(verbose_name='URL')),
                ('tableau_anno', models.IntegerField(default=0, null=True, verbose_name='Año')),
                ('tableau_estamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.estamento', verbose_name='Estamento')),
            ],
            options={
                'verbose_name': 'Tableau',
                'verbose_name_plural': 'Tableau',
                'db_table': 'Tableau',
                'ordering': ['tableau_title'],
            },
        ),
    ]
