# Generated by Django 4.0.3 on 2024-04-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0072_tableau'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='cronograma_cumplimiento_mes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cronograma_cumplimiento_mes', to='poa.mes', verbose_name='Mes Cumplimiento'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='cronograma_mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma_mes', to='poa.mes', verbose_name='Mes'),
        ),
    ]
