# Generated by Django 4.0.3 on 2024-04-08 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0073_cronograma_cronograma_cumplimiento_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='bug_poa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poa.poa', verbose_name='POA'),
        ),
        migrations.AddField(
            model_name='log',
            name='log_accion',
            field=models.CharField(default='', max_length=100, verbose_name='Acción'),
        ),
        migrations.AddField(
            model_name='log',
            name='log_poa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poa.poa', verbose_name='POA'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_description',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
