# Generated by Django 4.0.3 on 2024-05-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0075_rename_log_accion_log_log_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_poa',
            field=models.IntegerField(default=0, null=True, verbose_name='POA'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_user',
            field=models.IntegerField(default=0, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_poa',
            field=models.IntegerField(default=0, null=True, verbose_name='POA'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_user',
            field=models.IntegerField(default=0, verbose_name='Usuario'),
        ),
    ]
