# Generated by Django 4.0.3 on 2024-05-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0076_alter_bug_bug_poa_alter_bug_bug_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='bug_poaname',
            field=models.TextField(default='', null=True, verbose_name='POA'),
        ),
        migrations.AddField(
            model_name='bug',
            name='bug_username',
            field=models.TextField(default='', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='log',
            name='log_poaname',
            field=models.TextField(default='', null=True, verbose_name='POA'),
        ),
        migrations.AddField(
            model_name='log',
            name='log_username',
            field=models.TextField(default='', verbose_name='Usuario'),
        ),
    ]
