# Generated by Django 4.0.3 on 2024-05-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0077_bug_bug_poaname_bug_bug_username_log_log_poaname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tableau',
        ),
    ]
