# Generated by Django 4.0.3 on 2024-09-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0078_delete_tableau'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='cronograma_cumplimiento_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha Cumplimiento'),
        ),
    ]
