# Generated by Django 4.0.3 on 2022-03-13 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacion_type', models.IntegerField(choices=[(1, 'Notificación'), (2, 'Mensaje'), (3, 'Otro')], default=1, verbose_name='Tipo')),
                ('notificacion_message', models.CharField(max_length=250, verbose_name='Mensaje')),
                ('notificacion_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('notificacion_discharge', models.DateField(auto_now_add=True, verbose_name='Fecha alta')),
                ('notificacion_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to=settings.AUTH_USER_MODEL)),
                ('notificacion_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'Notification',
                'ordering': ['notificacion_discharge'],
            },
        ),
    ]
