# Generated by Django 4.0.3 on 2023-10-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_parametro_parametro_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parametro',
        ),
    ]
