# Generated by Django 4.0.3 on 2024-04-07 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_parametro'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('type_name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'TypeNotification',
                'verbose_name_plural': 'TypeNotifications',
                'db_table': 'TypeNotification',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificacion_discharge',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha envío'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificacion_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.typenotification', verbose_name='Tipo'),
        ),
    ]
