# Generated by Django 4.0.3 on 2024-04-11 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_rename_notification_notificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='notificacion_discharge',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha envío'),
        ),
    ]
