from django.urls import path
from .views import *

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('organization_chart', OrganizationChart.as_view(), name="organization_chart"),
    path('componente_chart', ComponenteChart.as_view(), name="componente_chart"),
    path('about', About.as_view(), name="about"),
    path('help', Help.as_view(), name="help"),
    path('poa_preview/<int:estamento_id>/<int:poa_anno>/<int:pag>', PoaPreview.as_view(), name="poa_preview"),
    path('poa_load', POALoad.as_view(), name="poa_load"),
    path('send_message', PoaSendMessage.as_view(), name="send_message"),
    path('refresh_notifications', RefreshNotifications.as_view(), name="refresh_notifications"),
    path('mark_notifications', MarkNotifications.as_view(), name="mark_notifications"),
    path('poa_card/<int:estamento_id>/<int:poa_anno>/<int:pag>', POACard.as_view(), name="poa_card"),
    path('poa_clone/<int:estamento_id>/<int:poa_anno>', POAClone.as_view(), name='poa_clone'),
    path('poa_edit/<int:estamento_id>/<int:poa_anno>', POAEdit.as_view(), name='poa_edit'),
    path('poa_edit_start/<int:estamento_id>/<int:poa_anno>', POAEditStart.as_view(), name='poa_edit_start'),
    path('poa_edit_update/<str:selected_name>/<int:selected_id>', POAEditUpdate.as_view(), name='poa_edit_update'),
    path('poa_to_doc/<int:estamento_id>/<int:poa_anno>/<str:doc_type>', POAtoDOC.as_view(), name="poa_to_doc"),
    path('poa_progreso/<int:estamento_id>/<int:poa_anno>/<int:pag>', POAProgreso.as_view(), name="poa_progreso"),
    path('poa_ejecutoria/<int:estamento_id>/<int:poa_anno>/<int:pag>', PoaEjecutoria.as_view(), name="poa_ejecutoria"),
    path('ejecutoria_to_doc/<int:estamento_id>/<int:poa_anno>/<str:doc_type>', EjecutoriaToDOC.as_view(), name="ejecutoria_to_doc"),
    path('poa_correlacion/<int:estamento_id>/<int:poa_anno>/<int:pag>', PoaCorrelacion.as_view(), name="poa_correlacion"),
    path('poa_cronograma_update/<int:cronograma_id>', PoaCronogramaUpdate.as_view(), name='poa_cronograma_update'),
    path('poa_cronograma/<int:estamento_id>/<int:poa_anno>', PoaCronograma.as_view(), name="poa_cronograma"),
    path('poa_tablero/<int:estamento_id>/<int:poa_anno>/<int:pag>', PoaTablero.as_view(), name="poa_tablero"),
    path('poa_tableau/<int:estamento_id>/<int:poa_anno>/<int:tableau_id>', PoaTableau.as_view(), name="poa_tableau"),
    path('poa_estado/<int:estamento_id>/<int:poa_anno>', POAEstado.as_view(), name="poa_estado"),
    path('poa_incluir_subs/<int:estamento_id>/<int:poa_anno>/<str:action>', POAIncluirSubs.as_view(), name="poa_incluir_subs"),
    path('cronograma_presupuesto', CronogramaPresupuesto.as_view(), name="cronograma_presupuesto"),
    path('poa_notas', POANotas.as_view(), name="poa_notas"),
    path('popover_notas', PopoverNotas.as_view(), name="popover_notas"),
    path('test_mail', TestMail, name="test_mail"),
    path('test_pdf', TestPDF, name="test_pdf"),
    path('test_word', TestWord, name="test_word"),
    path('test', Test, name="test"),
]
