# Generated by Django 4.0.3 on 2022-03-17 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinacion',
            name='coordinacion_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Coordinador(a)'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='departamento_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='J. Departamento'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Director(a)'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='unidad_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='J. Unidad'),
        ),
        migrations.AddField(
            model_name='vicerrectoria',
            name='vice_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vicerrector(a)'),
        ),
    ]
