# Generated by Django 4.0.3 on 2022-03-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0005_alter_coordinacion_coordinacion_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeparatamentoSub',
            new_name='DepartamentoSub',
        ),
    ]
