# Generated by Django 4.0.3 on 2022-03-17 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uapa', '0006_rename_deparatamentosub_departamentosub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuela_name', models.CharField(max_length=100, verbose_name='Escuela')),
                ('escuela_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
                'db_table': 'Escuela',
                'ordering': ['escuela_name'],
            },
        ),
        migrations.CreateModel(
            name='EscuelaSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuelasub_name', models.CharField(max_length=100, verbose_name='Escuela Subordinación')),
            ],
            options={
                'verbose_name': 'EscuelaSub',
                'verbose_name_plural': 'EscuelaSubs',
                'db_table': 'EscuelaSub',
                'ordering': ['escuelasub_name'],
            },
        ),
        migrations.CreateModel(
            name='EscuelaDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.direccion', verbose_name='Dirección')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.escuela', verbose_name='Escuela')),
            ],
            options={
                'verbose_name': 'EscuelaDireccion',
                'verbose_name_plural': 'EscuelaDireccions',
                'db_table': 'EscuelaDireccion',
                'ordering': ['escuela'],
            },
        ),
        migrations.AddField(
            model_name='escuela',
            name='escuela_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.escuelasub', verbose_name='Subordinación'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='escuela_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='J. Escuela'),
        ),
    ]
