# Generated by Django 4.0.3 on 2022-03-17 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0007_escuela_escuelasub_escueladireccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinacionEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.coordinacion', verbose_name='Coordinación')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.escuela', verbose_name='Escuela')),
            ],
            options={
                'verbose_name': 'CoordinacionEscuela',
                'verbose_name_plural': 'CoordinacionEscuelas',
                'db_table': 'CoordinacionEscuela',
                'ordering': ['coordinacion'],
            },
        ),
    ]
