# Generated by Django 4.0.3 on 2022-03-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0008_coordinacionescuela'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_name', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'Cargo',
                'ordering': ['cargo_name'],
            },
        ),
    ]
