# Generated by Django 4.0.3 on 2022-03-24 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0014_unidad_unidad_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinacion',
            name='coordinacion_cargo',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='uapa.cargo', verbose_name='Cargo'),
            preserve_default=False,
        ),
    ]
