# Generated by Django 4.0.3 on 2022-04-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0015_coordinacion_coordinacion_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cargo_code',
            field=models.CharField(blank=True, max_length=3, verbose_name='Código Cargo'),
        ),
    ]
