# Generated by Django 4.0.3 on 2022-04-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0016_cargo_cargo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo_code',
            field=models.CharField(max_length=3, verbose_name='Código Cargo'),
        ),
    ]
