# Generated by Django 4.0.3 on 2022-04-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0018_alter_cargo_cargo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo_code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Código Cargo'),
        ),
    ]
