# Generated by Django 4.0.3 on 2022-04-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0019_alter_cargo_cargo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_code', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('tipo_name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('tipo_cargo', models.CharField(max_length=100, unique=True, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'TipoEstamento',
                'verbose_name_plural': 'TipoEstamentos',
                'db_table': 'TipoEstamento',
                'ordering': ['tipo_name'],
            },
        ),
        migrations.CreateModel(
            name='Estamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estamento_name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('estamento_sub', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='uapa.estamento', verbose_name='Estamento Subordinado')),
                ('estamento_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.tipoestamento', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Estamento',
                'verbose_name_plural': 'Estamentos',
                'db_table': 'Estamento',
                'ordering': ['estamento_name'],
            },
        ),
    ]
