# Generated by Django 4.0.3 on 2022-04-22 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uapa', '0020_tipoestamento_estamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estamento',
            name='estamento_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vicerrector(a)'),
            preserve_default=False,
        ),
    ]
