# Generated by Django 4.0.3 on 2022-04-23 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0021_estamento_estamento_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoestamento',
            options={'ordering': ['id'], 'verbose_name': 'TipoEstamento', 'verbose_name_plural': 'TipoEstamentos'},
        ),
        migrations.AddField(
            model_name='estamento',
            name='estamento_sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uapa.sede', verbose_name='Sede'),
            preserve_default=False,
        ),
    ]
