# Generated by Django 4.0.3 on 2022-04-23 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0022_alter_tipoestamento_options_estamento_estamento_sede'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['id'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AlterField(
            model_name='estamento',
            name='estamento_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uapa.estamento', verbose_name='Estamento Subordinado'),
        ),
    ]
