# Generated by Django 4.0.3 on 2024-03-11 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uapa', '0026_alter_tipoestamento_tipo_faicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estamento',
            name='estamento_user',
        ),
        migrations.AddField(
            model_name='estamento',
            name='estamento_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
