# Generated by Django 4.0.3 on 2024-03-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0029_remove_tipoestamento_tipo_faicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoestamento',
            name='tipo_faicon',
            field=models.CharField(default='', max_length=100, verbose_name='Fa Icon'),
        ),
    ]
