# Generated by Django 4.0.3 on 2024-03-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0030_tipoestamento_tipo_faicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estamento',
            name='estamento_has_poa',
        ),
    ]
