# Generated by Django 4.0.3 on 2024-03-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0031_remove_estamento_estamento_has_poa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estamento',
            name='estamento_has_poa',
            field=models.BooleanField(default=False, verbose_name='Tiene POA'),
        ),
    ]
