# Generated by Django 4.0.3 on 2024-03-11 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uapa', '0032_estamento_estamento_has_poa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estamento',
            name='estamento_user',
        ),
        migrations.AddField(
            model_name='estamento',
            name='estamento_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vicerrector(a)'),
        ),
    ]
