# Generated by Django 4.0.3 on 2024-03-11 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uapa', '0033_remove_estamento_estamento_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador_can_edit', models.BooleanField(default=False, verbose_name='Puede editar')),
                ('colaborador_estamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapa.estamento', verbose_name='Estamento')),
                ('colaborador_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'db_table': 'Colaborador',
                'ordering': ['colaborador_estamento'],
            },
        ),
        migrations.AddConstraint(
            model_name='colaborador',
            constraint=models.UniqueConstraint(fields=('colaborador_user', 'colaborador_estamento'), name='unique_colaborador'),
        ),
    ]
