# Generated by Django 4.0.3 on 2024-04-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uapa', '0034_colaborador_colaborador_unique_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='estamento',
            name='estamento_roots',
            field=models.TextField(default='', verbose_name='Lista de roots'),
        ),
        migrations.AlterField(
            model_name='estamento',
            name='estamento_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uapa.tipoestamento', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tipoestamento',
            name='tipo_faicon',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Fa Icon'),
        ),
    ]
